
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - POSTGRES_DB=nombre_basedatos
      - POSTGRES_USER=usuario
      - POSTGRES_PASSWORD=contraseña
      - CELERY_BROKER_URL=redis://redis:6379/0  # Conexión con Redis
    depends_on:
      - db
      - redis
      - celery

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: nombre_basedatos
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: contraseña
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  celery:
    build: .
    command: celery -A task_manager worker --loglevel=info  
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
volumes:
  postgres_data: