
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://facu:faguileradev@rds-dbpruebas.cbkk0kmgy8f6.us-east-2.rds.amazonaws.com:5432/dbpruebas
      DB_HOST: dbpruebas.cbkk0kmgy8f6.us-east-2.rds.amazonaws.com
      DB_PORT: 5432
      DB_NAME: dbpruebas
      DB_USER: facu
      DB_PASSWORD: faguileradev
      CELERY_BROKER_URL: redis://redis:6379/0  # Conexión con Redis
    depends_on:
      - redis
      - celery
    networks:
      - app-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

  celery:
    build: .
    command: celery -A task_manager worker --loglevel=info
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgres://facu:faguileradev@rds-dbpruebas.cbkk0kmgy8f6.us-east-2.rds.amazonaws.com:5432/dbpruebas
      CELERY_BROKER_URL: redis://redis:6379/0
    depends_on:
      - redis
    networks:
      - app-network

  migrate:
    build: .
    command: python manage.py migrate
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgres://facu:faguileradev@rds-dbpruebas.cbkk0kmgy8f6.us-east-2.rds.amazonaws.com:5432/dbpruebas
    depends_on:
      - redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

