
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - POSTGRES_DB=dbpruebas
      - POSTGRES_USER=facu
      - POSTGRES_PASSWORD=faguileradev
      - CELERY_BROKER_URL=redis://redis:6379/0  # Conexión con Redis
    depends_on:
      - db
      - redis
      - celery

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  celery:
    build: .
    command: celery -A task_manager worker --loglevel=info  
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
  migrate:
    image: postgres:16.6
    container_name: db_migrator
    entrypoint: ["sh", "-c", "until pg_isready -h dbpruebas.cbkk0kmgy8f6.us-east-2.rds.amazonaws.com -U facu; do sleep 1; done && python manage.py migrate"]
    environment:
      PGPASSWORD: faguileradev
    networks:
      - app-network

networks:
  app-network:
    driver: bridge